name: countinus integration and deployment

on:
    push:
        branches:
            - main
            
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '8.0.x' ]
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - name: checkout dotnet
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
          

          
      - name: Start SQL
        run: docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=yourStrong(!)Password" -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-latest

      - name: restore dependencies
        run: dotnet restore


      - name: Execute dotnet Build
        run: dotnet build -c Release

      - name: run test Automate
        env:
          ConnectionStrings__DefaultConnection: "server=localhost;Database=customer;User=sa;Password=yourStrong(!)Password;"
        run: dotnet test -c Release

      # - name: deploy on Azure
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: my_app_env_on_azure
      #     publish-profile: ${{ secrets.ASP_EXAMPLE_Azure_Publish }}