name: countinus integration and deployment

on:
    push:
        branches:
            - main
            
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '8.0.x' ]
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - name: checkout dotnet
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}


      - name: restore dependencies
        run: dotnet restore


      - name: Execute dotnet Build
        run: dotnet build  -C Release